include_guard(GLOBAL)

function(_dagflow_project_diagnostics_finalize)
  get_property(_mode GLOBAL PROPERTY DAGFLOW_PROJECT_MODE)
  get_property(_caps GLOBAL PROPERTY DAGFLOW_ACTIVE_PROJECT_CAPABILITIES)
  get_property(_expanded_caps GLOBAL PROPERTY DAGFLOW_ACTIVE_PROJECT_CAPABILITIES_EXPANDED)
  dagflow_collect_targets("${CMAKE_SOURCE_DIR}" _targets)
  set(_summary "DagFlow project summary\n")
  string(APPEND _summary "  project: ${CMAKE_PROJECT_NAME} ${CMAKE_PROJECT_VERSION}\n")
  string(APPEND _summary "  mode: ${_mode}\n")
  string(APPEND _summary "  capabilities: ${_caps}\n")
  string(APPEND _summary "  capabilities (expanded): ${_expanded_caps}\n")
  string(APPEND _summary "  generator: ${CMAKE_GENERATOR}\n")
  string(APPEND _summary "  compiler: ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}\n")
  string(APPEND _summary "  system: ${CMAKE_SYSTEM_NAME} ${CMAKE_SYSTEM_PROCESSOR}\n")
  string(APPEND _summary "  dependency provider: ${DAGFLOW_DEPENDENCY_PROVIDER}\n")
  string(APPEND _summary "  targets:\n")
  foreach(_target IN LISTS _targets)
    get_target_property(_type ${_target} TYPE)
    if(_type STREQUAL "UTILITY")
      continue()
    endif()
    get_target_property(_policies ${_target} DAGFLOW_POLICIES)
    if(NOT _policies OR _policies MATCHES "-NOTFOUND$")
      set(_policies "<project-defaults>")
    endif()
    string(APPEND _summary "    - ${_target} [${_type}] policies=${_policies}\n")
  endforeach()
  set(_path "${CMAKE_BINARY_DIR}/dagflow-project.txt")
  file(WRITE "${_path}" "${_summary}")
  message(STATUS "${_summary}")
  if(NOT TARGET dagflow_config)
    add_custom_target(dagflow_config
      COMMAND "${CMAKE_COMMAND}" -E cat "${_path}" VERBATIM)
    set_property(TARGET dagflow_config PROPERTY FOLDER "dagflow")
  endif()
endfunction()
