include_guard(GLOBAL)
include(GNUInstallDirs)
set(DAGFLOW_PACKAGE_VENDOR "${PROJECT_NAME}" CACHE STRING "Package vendor")
set(DAGFLOW_PACKAGE_CONTACT "" CACHE STRING "Package maintainer/contact")
set(DAGFLOW_PACKAGE_SUMMARY "${PROJECT_DESCRIPTION}" CACHE STRING "Package summary")
set(DAGFLOW_PACKAGE_GENERATORS "" CACHE STRING "Explicit CPack generators; empty selects platform defaults")
set(DAGFLOW_DEB_DEPENDS "" CACHE STRING "Optional Debian package dependency expression")
set(DAGFLOW_RPM_REQUIRES "" CACHE STRING "Optional RPM package dependency expression")

function(_dagflow_project_packaging_finalize)
  include(InstallRequiredSystemLibraries)
  set(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
  set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
  set(CPACK_PACKAGE_VENDOR "${DAGFLOW_PACKAGE_VENDOR}")
  set(CPACK_PACKAGE_CONTACT "${DAGFLOW_PACKAGE_CONTACT}")
  set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${DAGFLOW_PACKAGE_SUMMARY}")
  if(EXISTS "${CMAKE_SOURCE_DIR}/LICENSE")
    set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")
  endif()
  set(CPACK_STRIP_FILES TRUE)
  set(CPACK_COMPONENTS_ALL Runtime Development Documentation)
  set(CPACK_COMPONENT_RUNTIME_DISPLAY_NAME "Runtime")
  set(CPACK_COMPONENT_DEVELOPMENT_DISPLAY_NAME "Development")
  set(CPACK_COMPONENT_DOCUMENTATION_DISPLAY_NAME "Documentation")
  set(CPACK_COMPONENT_DEVELOPMENT_DEPENDS Runtime)

  if(DAGFLOW_PACKAGE_GENERATORS)
    set(CPACK_GENERATOR "${DAGFLOW_PACKAGE_GENERATORS}")
  elseif(WIN32)
    set(CPACK_GENERATOR NSIS)
    set(CPACK_NSIS_MODIFY_PATH ON)
    set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
  elseif(APPLE)
    set(CPACK_GENERATOR TGZ DragNDrop)
  elseif(UNIX)
    set(CPACK_GENERATOR TGZ DEB RPM)
  else()
    set(CPACK_GENERATOR TGZ)
  endif()

  if(UNIX AND NOT APPLE)
    if(DAGFLOW_PACKAGE_CONTACT)
      set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${DAGFLOW_PACKAGE_CONTACT}")
    else()
      set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${DAGFLOW_PACKAGE_VENDOR}")
    endif()
    set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
    set(CPACK_RPM_FILE_NAME RPM-DEFAULT)
    if(DAGFLOW_DEB_DEPENDS)
      set(CPACK_DEBIAN_PACKAGE_DEPENDS "${DAGFLOW_DEB_DEPENDS}")
    endif()
    if(DAGFLOW_RPM_REQUIRES)
      set(CPACK_RPM_PACKAGE_REQUIRES "${DAGFLOW_RPM_REQUIRES}")
    endif()
  endif()

  get_property(_revision GLOBAL PROPERTY DAGFLOW_GIT_SHORT_SHA)
  if(NOT _revision)
    set(_revision unknown)
  endif()
  if(CMAKE_CONFIGURATION_TYPES)
    set(_build multi)
  elseif(CMAKE_BUILD_TYPE)
    set(_build "${CMAKE_BUILD_TYPE}")
  else()
    set(_build default)
  endif()
  set(CPACK_PACKAGE_FILE_NAME
    "${PROJECT_NAME}-${PROJECT_VERSION}-${_revision}-${CMAKE_SYSTEM_NAME}-${_build}-${CMAKE_CXX_COMPILER_ID}")
  include(CPack)
endfunction()
