include_guard(GLOBAL)
set(DAGFLOW_WEB_DIST "${CMAKE_BINARY_DIR}/web-dist" CACHE PATH "Emscripten deployment output")

function(dagflow_register_web_target target)
  if(NOT TARGET ${target})
    message(FATAL_ERROR "dagflow_register_web_target: unknown target ${target}")
  endif()
  set_property(GLOBAL APPEND PROPERTY DAGFLOW_WEB_TARGETS ${target})
endfunction()

function(_dagflow_project_web_finalize)
  if(NOT EMSCRIPTEN)
    message(STATUS "DagFlow: web-deployment capability is inactive outside Emscripten")
    return()
  endif()
  get_property(_targets GLOBAL PROPERTY DAGFLOW_WEB_TARGETS)
  if(NOT _targets)
    return()
  endif()
  file(MAKE_DIRECTORY "${DAGFLOW_WEB_DIST}")
  add_custom_target(web-dist)
  foreach(_target IN LISTS _targets)
    add_custom_command(TARGET ${_target} POST_BUILD
      COMMAND "${CMAKE_COMMAND}" -E copy_if_different "$<TARGET_FILE:${_target}>" "${DAGFLOW_WEB_DIST}/"
      VERBATIM)
    add_dependencies(web-dist ${_target})
  endforeach()
endfunction()
