include_guard(GLOBAL)

option(DAGFLOW_DIAGNOSTICS_VERBOSE
  "Print the full component/target diagnostics during configure" OFF)

function(_dagflow_project_diagnostics_finalize)
  get_property(_mode GLOBAL PROPERTY DAGFLOW_PROJECT_MODE)
  get_property(_caps GLOBAL PROPERTY DAGFLOW_ACTIVE_PROJECT_CAPABILITIES)
  get_property(_expanded_caps GLOBAL PROPERTY DAGFLOW_ACTIVE_PROJECT_CAPABILITIES_EXPANDED)
  dagflow_collect_project_targets(_targets)
  set(_real_target_count 0)
  foreach(_target IN LISTS _targets)
    get_target_property(_type ${_target} TYPE)
    if(NOT _type STREQUAL "UTILITY")
      math(EXPR _real_target_count "${_real_target_count}+1")
    endif()
  endforeach()
  set(_component_count 0)
  set(_summary "DagFlow project summary\n")
  string(APPEND _summary "  project: ${CMAKE_PROJECT_NAME} ${CMAKE_PROJECT_VERSION}\n")
  string(APPEND _summary "  mode: ${_mode}\n")
  string(APPEND _summary "  capabilities: ${_caps}\n")
  string(APPEND _summary "  capabilities (expanded): ${_expanded_caps}\n")
  string(APPEND _summary "  generator: ${CMAKE_GENERATOR}\n")
  string(APPEND _summary "  compiler: ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}\n")
  string(APPEND _summary "  system: ${CMAKE_SYSTEM_NAME} ${CMAKE_SYSTEM_PROCESSOR}\n")
  string(APPEND _summary "  dependency provider: ${DAGFLOW_DEPENDENCY_PROVIDER}\n")
  if(COMMAND dagflow_list_components)
    dagflow_list_components(_components)
    if(_components)
      list(LENGTH _components _component_count)
      string(APPEND _summary "  components:\n")
      foreach(_component IN LISTS _components)
        dagflow_component_property("${_component}" SOURCE_DIR _component_source)
        dagflow_component_targets("${_component}" _component_targets)
        list(LENGTH _component_targets _component_target_count)
        string(APPEND _summary
          "    - ${_component}: targets=${_component_target_count} source=${_component_source}\n")
      endforeach()
    endif()
  endif()
  string(APPEND _summary "  targets:\n")
  foreach(_target IN LISTS _targets)
    get_target_property(_type ${_target} TYPE)
    if(_type STREQUAL "UTILITY")
      continue()
    endif()
    get_target_property(_role ${_target} DAGFLOW_ARTIFACT_ROLE)
    if(NOT _role OR _role MATCHES "-NOTFOUND$")
      set(_role "UNCLASSIFIED")
    endif()
    get_target_property(_policies ${_target} DAGFLOW_POLICIES)
    if(NOT _policies OR _policies MATCHES "-NOTFOUND$")
      set(_policies "<project-defaults>")
    endif()
    get_target_property(_component ${_target} DAGFLOW_COMPONENT)
    if(NOT _component OR _component MATCHES "-NOTFOUND$")
      set(_component "<workspace>")
    endif()
    string(APPEND _summary
      "    - ${_target} [${_type}] component=${_component} role=${_role} policies=${_policies}\n")
  endforeach()
  set(_path "${CMAKE_BINARY_DIR}/dagflow-project.txt")
  file(WRITE "${_path}" "${_summary}")
  if(DAGFLOW_DIAGNOSTICS_VERBOSE)
    message(STATUS "${_summary}")
  else()
    message(STATUS
      "DagFlow diagnostics: components=${_component_count}, targets=${_real_target_count}; details=${_path}")
  endif()
  if(NOT TARGET dagflow_config)
    add_custom_target(dagflow_config
      COMMAND "${CMAKE_COMMAND}" -E cat "${_path}" VERBATIM)
    set_property(TARGET dagflow_config PROPERTY FOLDER "dagflow")
  endif()
endfunction()
