include_guard(GLOBAL)

function(_dagflow_collect_policy_args output policies policy_options)
  set(_args)
  if(policies)
    list(APPEND _args POLICIES ${policies})
  endif()
  if(policy_options)
    list(APPEND _args POLICY_OPTIONS ${policy_options})
  endif()
  set(${output} "${_args}" PARENT_SCOPE)
endfunction()

# Examples are executable workloads, not a second target model. This helper
# composes the existing executable/scenario/check/PGO primitives and provides a
# common build aggregate. Long execution remains explicit through run_<name> or
# run_group_examples; the default build only compiles the example binaries.
function(dagflow_add_example target)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "SMOKE;PGO;INSTALL"
    "TIMEOUT;REPEATS;WARMUP;WORKING_DIRECTORY"
    "SOURCES;LIBRARIES;ARGS;SMOKE_ARGS;PGO_ARGS;ENVIRONMENT;LABELS;POLICIES;POLICY_OPTIONS")
  if(ARG_UNPARSED_ARGUMENTS OR NOT ARG_SOURCES)
    message(FATAL_ERROR "dagflow_add_example requires SOURCES; invalid arguments for ${target}")
  endif()
  if(ARG_SMOKE_ARGS AND NOT ARG_SMOKE)
    message(FATAL_ERROR "dagflow_add_example(${target}): SMOKE_ARGS requires SMOKE")
  endif()
  if(ARG_PGO_ARGS AND NOT ARG_PGO)
    message(FATAL_ERROR "dagflow_add_example(${target}): PGO_ARGS requires PGO")
  endif()

  _dagflow_collect_policy_args(_policy_args "${ARG_POLICIES}" "${ARG_POLICY_OPTIONS}")
  set(_executable_options)
  if(ARG_INSTALL)
    list(APPEND _executable_options INSTALL)
  endif()
  dagflow_add_executable(${target} ${_executable_options}
    SOURCES ${ARG_SOURCES} LIBRARIES ${ARG_LIBRARIES} ${_policy_args})

  if(NOT TARGET dagflow_examples)
    add_custom_target(dagflow_examples)
  endif()
  add_dependencies(dagflow_examples ${target})

  set(_scenario_options TARGET ${target} GROUP examples ARGS ${ARG_ARGS}
    ENVIRONMENT ${ARG_ENVIRONMENT} LABELS example ${ARG_LABELS})
  foreach(_field IN ITEMS TIMEOUT REPEATS WARMUP WORKING_DIRECTORY)
    if(DEFINED ARG_${_field} AND NOT "${ARG_${_field}}" STREQUAL "")
      list(APPEND _scenario_options ${_field} "${ARG_${_field}}")
    endif()
  endforeach()
  if(ARG_SMOKE)
    list(APPEND _scenario_options SMOKE SMOKE_ARGS ${ARG_SMOKE_ARGS})
  endif()
  if(ARG_PGO)
    list(APPEND _scenario_options PGO PGO_ARGS ${ARG_PGO_ARGS})
  endif()
  dagflow_add_scenario(${target} ${_scenario_options})
endfunction()

function(dagflow_benchmark_enabled output target group)
  string(MAKE_C_IDENTIFIER "${target}" _key)
  string(TOUPPER "${_key}" _key)
  option(DAGFLOW_BUILD_${_key} "Build benchmark ${target}" ON)
  set(_enabled FALSE)
  if(DAGFLOW_BUILD_${_key} AND ("all" IN_LIST DAGFLOW_BENCHMARK_GROUPS OR
      "${group}" IN_LIST DAGFLOW_BENCHMARK_GROUPS))
    set(_enabled TRUE)
  endif()
  set(${output} "${_enabled}" PARENT_SCOPE)
endfunction()

function(dagflow_add_benchmark target)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "" "GROUP;REPEATS;WARMUP" "SOURCES;LIBRARIES;ARGS;POLICIES;POLICY_OPTIONS")
  if(ARG_UNPARSED_ARGUMENTS OR NOT ARG_SOURCES)
    message(FATAL_ERROR "dagflow_add_benchmark requires SOURCES; invalid arguments")
  endif()
  if(NOT ARG_GROUP)
    set(ARG_GROUP custom)
  endif()
  dagflow_benchmark_enabled(_enabled "${target}" "${ARG_GROUP}")
  if(NOT _enabled)
    return()
  endif()
  _dagflow_collect_policy_args(_policy_args "${ARG_POLICIES}" "${ARG_POLICY_OPTIONS}")
  dagflow_add_executable(${target} SOURCES ${ARG_SOURCES} LIBRARIES ${ARG_LIBRARIES} ${_policy_args})
  foreach(_aggregate IN ITEMS dagflow_benchmarks benchmarks_${ARG_GROUP})
    if(NOT TARGET ${_aggregate})
      add_custom_target(${_aggregate})
    endif()
    add_dependencies(${_aggregate} ${target})
  endforeach()
  set(_run_options)
  foreach(_field IN ITEMS REPEATS WARMUP)
    if(DEFINED ARG_${_field})
      list(APPEND _run_options ${_field} "${ARG_${_field}}")
    endif()
  endforeach()
  dagflow_add_scenario(${target} TARGET ${target} GROUP ${ARG_GROUP} ARGS ${ARG_ARGS} ${_run_options})
endfunction()

function(dagflow_add_test target)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "" "TIMEOUT;WORKING_DIRECTORY" "SOURCES;LIBRARIES;ARGS;LABELS;ENVIRONMENT;POLICIES;POLICY_OPTIONS")
  if(ARG_UNPARSED_ARGUMENTS OR NOT ARG_SOURCES)
    message(FATAL_ERROR "dagflow_add_test requires SOURCES; invalid arguments")
  endif()
  if(NOT BUILD_TESTING)
    return()
  endif()
  _dagflow_collect_policy_args(_policy_args "${ARG_POLICIES}" "${ARG_POLICY_OPTIONS}")
  dagflow_add_executable(${target} SOURCES ${ARG_SOURCES} LIBRARIES ${ARG_LIBRARIES} ${_policy_args})
  set(_optional)
  foreach(_field IN ITEMS TIMEOUT WORKING_DIRECTORY)
    if(ARG_${_field})
      list(APPEND _optional ${_field} "${ARG_${_field}}")
    endif()
  endforeach()
  dagflow_register_check(${target} ${target} ARGS ${ARG_ARGS}
    LABELS unit ${ARG_LABELS} ENVIRONMENT ${ARG_ENVIRONMENT} ${_optional})
endfunction()



function(dagflow_add_property_test target)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "" "BACKEND" "SOURCES;LIBRARIES;LABELS;POLICIES;POLICY_OPTIONS")
  if(ARG_UNPARSED_ARGUMENTS OR NOT ARG_SOURCES)
    message(FATAL_ERROR "dagflow_add_property_test requires SOURCES")
  endif()
  if(NOT BUILD_TESTING)
    return()
  endif()
  if(NOT ARG_BACKEND)
    set(ARG_BACKEND "${DAGFLOW_PBT_BACKEND}")
  endif()
  if(NOT ARG_BACKEND STREQUAL "rapidcheck")
    message(FATAL_ERROR "Unsupported property-testing backend: ${ARG_BACKEND}")
  endif()
  dagflow_require_googletest()
  dagflow_require_rapidcheck()
  _dagflow_collect_policy_args(_policy_args "${ARG_POLICIES}" "${ARG_POLICY_OPTIONS}")
  dagflow_add_executable(${target} SOURCES ${ARG_SOURCES}
    LIBRARIES ${ARG_LIBRARIES} rapidcheck rapidcheck_gtest GTest::gtest_main ${_policy_args})
  include(GoogleTest)
  dagflow_discover_tests(${target} TEST_PREFIX "${target}." DISCOVERY_MODE PRE_TEST
    PROPERTIES TIMEOUT 30 LABELS "unit;property;pbt;rapidcheck;${ARG_LABELS}")
  if(NOT TARGET dagflow_tests)
    add_custom_target(dagflow_tests)
  endif()
  add_dependencies(dagflow_tests ${target})
  set_property(GLOBAL APPEND PROPERTY DAGFLOW_PROPERTY_TEST_TARGETS ${target})
endfunction()

function(_dagflow_fuzz_sanitizer_flags output)
  if(DAGFLOW_FUZZ_SANITIZER STREQUAL "none")
    set(_flags)
  elseif(DAGFLOW_FUZZ_SANITIZER STREQUAL "address")
    set(_flags -fsanitize=address)
  elseif(DAGFLOW_FUZZ_SANITIZER STREQUAL "undefined")
    set(_flags -fsanitize=undefined)
  elseif(DAGFLOW_FUZZ_SANITIZER STREQUAL "address-undefined")
    set(_flags -fsanitize=address,undefined)
  else()
    message(FATAL_ERROR "Unsupported DAGFLOW_FUZZ_SANITIZER=${DAGFLOW_FUZZ_SANITIZER}")
  endif()
  set(${output} "${_flags}" PARENT_SCOPE)
endfunction()

# A separate archive keeps coverage and sanitizer instrumentation out of normal
# libraries, installed packages and applications in the same build tree.
function(dagflow_add_fuzz_library target)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "" "BACKEND" "SOURCES;LIBRARIES;POLICIES;POLICY_OPTIONS")
  if(ARG_UNPARSED_ARGUMENTS OR ARG_KEYWORDS_MISSING_VALUES OR NOT ARG_SOURCES)
    message(FATAL_ERROR "dagflow_add_fuzz_library requires SOURCES")
  endif()
  if(NOT ARG_BACKEND)
    set(ARG_BACKEND "${DAGFLOW_FUZZ_BACKEND}")
  endif()
  _dagflow_validate_link_dependencies(${target} ${ARG_LIBRARIES})
  add_library(${target} STATIC ${ARG_SOURCES})
  dagflow_set_artifact_role(${target} LIBRARY)
  target_link_libraries(${target} PUBLIC ${ARG_LIBRARIES})
  dagflow_apply_target_policy(${target} POLICIES minimal frame-pointers ${ARG_POLICIES}
    SANITIZER none PGO_MODE none LTO_MODE none ${ARG_POLICY_OPTIONS})
  _dagflow_instrument_fuzz_target(${target} "${ARG_BACKEND}")
endfunction()

function(_dagflow_instrument_fuzz_target target backend)
  get_filename_component(_compiler_name "${CMAKE_CXX_COMPILER}" NAME)
  if(backend STREQUAL "libfuzzer")
    if(MSVC OR NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang")
      message(FATAL_ERROR "libFuzzer backend requires GNU-style Clang/AppleClang")
    endif()
  elseif(backend STREQUAL "aflpp")
    if(NOT _compiler_name MATCHES "^afl-")
      message(FATAL_ERROR "AFL++ backend requires an AFL++ compiler wrapper")
    endif()
  elseif(backend STREQUAL "honggfuzz")
    if(NOT _compiler_name MATCHES "^hfuzz-")
      message(FATAL_ERROR "honggfuzz backend requires an hfuzz compiler wrapper")
    endif()
  else()
    message(FATAL_ERROR "Unsupported fuzz backend: ${backend}")
  endif()
  _dagflow_fuzz_sanitizer_flags(_san_flags)
  target_compile_definitions(${target} PRIVATE FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION=1)
  target_compile_options(${target} PRIVATE -O1 -g -fno-omit-frame-pointer
    -fno-sanitize-recover=all ${_san_flags})
  if(NOT backend STREQUAL "honggfuzz")
    target_compile_options(${target} PRIVATE -fsanitize=fuzzer-no-link)
  endif()
  set_property(TARGET ${target} PROPERTY DAGFLOW_FUZZ_BACKEND "${backend}")
  set_property(TARGET ${target} PROPERTY DAGFLOW_FUZZ_SANITIZER "${DAGFLOW_FUZZ_SANITIZER}")
endfunction()

function(_dagflow_prepare_fuzz_dirs target corpus_arg output_corpus output_artifacts)
  if(corpus_arg)
    get_filename_component(_corpus "${corpus_arg}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
  else()
    set(_corpus "${CMAKE_CURRENT_BINARY_DIR}/${target}-corpus")
  endif()
  set(_artifacts "${CMAKE_CURRENT_BINARY_DIR}/${target}-artifacts")
  file(MAKE_DIRECTORY "${_corpus}" "${_artifacts}")
  if(NOT EXISTS "${_corpus}/dagflow-seed")
    file(WRITE "${_corpus}/dagflow-seed" "0")
  endif()
  set(${output_corpus} "${_corpus}" PARENT_SCOPE)
  set(${output_artifacts} "${_artifacts}" PARENT_SCOPE)
endfunction()

# One harness API, multiple engines. The harness source always exports
# LLVMFuzzerTestOneInput(). AFL++ and honggfuzz require their compiler wrapper
# to be selected before project() (normally through a configure preset).
function(dagflow_add_fuzzer target)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "" "BACKEND;CORPUS;SEED_CORPUS;DICTIONARY;RUN_SECONDS;MAX_LEN"
    "SOURCES;LIBRARIES;POLICIES;POLICY_OPTIONS")
  if(ARG_UNPARSED_ARGUMENTS OR ARG_KEYWORDS_MISSING_VALUES OR NOT ARG_SOURCES)
    message(FATAL_ERROR "dagflow_add_fuzzer requires SOURCES and complete keyword values")
  endif()
  if(NOT ARG_BACKEND)
    set(ARG_BACKEND "${DAGFLOW_FUZZ_BACKEND}")
  endif()
  if(NOT ARG_BACKEND MATCHES "^(libfuzzer|aflpp|honggfuzz)$")
    message(FATAL_ERROR "Unsupported fuzz backend: ${ARG_BACKEND}")
  endif()
  if(NOT DEFINED ARG_RUN_SECONDS)
    set(ARG_RUN_SECONDS "${DAGFLOW_FUZZ_RUNTIME}")
  endif()
  if(NOT ARG_RUN_SECONDS MATCHES "^[1-9][0-9]*$" OR
      (DEFINED ARG_MAX_LEN AND NOT ARG_MAX_LEN MATCHES "^[1-9][0-9]*$"))
    message(FATAL_ERROR "Fuzz RUN_SECONDS and MAX_LEN must be positive integers")
  endif()
  if(ARG_CORPUS AND ARG_SEED_CORPUS)
    message(FATAL_ERROR "Use CORPUS (mutable working corpus) or SEED_CORPUS (read-only seeds), not both")
  endif()
  if(ARG_SEED_CORPUS)
    get_filename_component(_seeds "${ARG_SEED_CORPUS}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    if(NOT IS_DIRECTORY "${_seeds}")
      message(FATAL_ERROR "Fuzz seed directory does not exist: ${_seeds}")
    endif()
    file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/${target}-corpus")
    file(COPY "${_seeds}/" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/${target}-corpus")
  endif()
  _dagflow_prepare_fuzz_dirs(${target} "${ARG_CORPUS}" _corpus _artifacts)
  _dagflow_fuzz_sanitizer_flags(_san_flags)

  set(_policies minimal frame-pointers ${ARG_POLICIES})
  set(_policy_options SANITIZER none PGO_MODE none LTO_MODE none ${ARG_POLICY_OPTIONS})
  dagflow_add_executable(${target} SOURCES ${ARG_SOURCES} LIBRARIES ${ARG_LIBRARIES}
    POLICIES ${_policies} POLICY_OPTIONS ${_policy_options})
  _dagflow_instrument_fuzz_target(${target} "${ARG_BACKEND}")
  foreach(_library IN LISTS ARG_LIBRARIES)
    if(TARGET ${_library})
      get_target_property(_backend ${_library} DAGFLOW_FUZZ_BACKEND)
      get_target_property(_sanitizer ${_library} DAGFLOW_FUZZ_SANITIZER)
      if(_backend AND (NOT _backend STREQUAL ARG_BACKEND OR NOT _sanitizer STREQUAL DAGFLOW_FUZZ_SANITIZER))
        message(FATAL_ERROR "Fuzzer ${target} and library ${_library} require matching backend and sanitizer")
      endif()
    endif()
  endforeach()

  get_filename_component(_compiler_name "${CMAKE_CXX_COMPILER}" NAME)
  dagflow_target_execution(${target} _runnable _emulator)
  if(CMAKE_CROSSCOMPILING AND NOT ARG_BACKEND STREQUAL "libfuzzer")
    message(FATAL_ERROR "Cross fuzzing with ${ARG_BACKEND} requires a backend-specific target runner; use a native build or libfuzzer")
  endif()
  set(_run_target "fuzz_${target}")
  set(_smoke_name "${target}")
  set(_dictionary_arg)

  if(ARG_BACKEND STREQUAL "libfuzzer")
    if(MSVC OR NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang")
      message(FATAL_ERROR "libFuzzer backend requires GNU-style Clang/AppleClang")
    endif()
    target_link_options(${target} PRIVATE -fsanitize=fuzzer ${_san_flags})
    if(NOT DAGFLOW_FUZZ_TIMEOUT MATCHES "^[1-9][0-9]*$")
      message(FATAL_ERROR "DAGFLOW_FUZZ_TIMEOUT must be a positive integer")
    endif()
    set(_run_args "${_corpus}" "-max_total_time=${ARG_RUN_SECONDS}" "-timeout=${DAGFLOW_FUZZ_TIMEOUT}" "-artifact_prefix=${_artifacts}/")
    set(_smoke_args "${_corpus}" -runs=1 "-timeout=${DAGFLOW_FUZZ_TIMEOUT}" "-artifact_prefix=${_artifacts}/")
    if(ARG_MAX_LEN)
      list(APPEND _run_args "-max_len=${ARG_MAX_LEN}")
      list(APPEND _smoke_args "-max_len=${ARG_MAX_LEN}")
    endif()
    if(ARG_DICTIONARY)
      get_filename_component(_dict "${ARG_DICTIONARY}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
      list(APPEND _run_args "-dict=${_dict}")
      list(APPEND _smoke_args "-dict=${_dict}")
    endif()
    if(_runnable)
      add_custom_target(${_run_target}
        COMMAND ${_emulator} "$<TARGET_FILE:${target}>" ${_run_args}
        DEPENDS ${target} USES_TERMINAL VERBATIM)
    endif()
    if(BUILD_TESTING)
      dagflow_register_check(${_smoke_name} ${target} ARGS ${_smoke_args}
        LABELS fuzz smoke libfuzzer ${DAGFLOW_FUZZ_SMOKE_LABEL} TIMEOUT 30)
    endif()

  elseif(ARG_BACKEND STREQUAL "aflpp")
    if(NOT _compiler_name MATCHES "^afl-")
      message(FATAL_ERROR
        "AFL++ backend requires configuring CMAKE_CXX_COMPILER to an AFL++ wrapper (for example afl-clang-fast++ or afl-clang-lto++).")
    endif()
    find_program(DAGFLOW_AFL_FUZZ NAMES afl-fuzz REQUIRED NO_CMAKE_FIND_ROOT_PATH)
    find_program(DAGFLOW_AFL_SHOWMAP NAMES afl-showmap REQUIRED NO_CMAKE_FIND_ROOT_PATH)
    # AFL++ recognizes -fsanitize=fuzzer and injects its libFuzzer-compatible
    # persistent driver for LLVMFuzzerTestOneInput().
    target_link_options(${target} PRIVATE -fsanitize=fuzzer ${_san_flags})
    file(MAKE_DIRECTORY "${_artifacts}/afl" "${_artifacts}/afl-showmap")
    set(_afl_args -i "${_corpus}" -o "${_artifacts}/afl" -V "${ARG_RUN_SECONDS}")
    if(ARG_MAX_LEN)
      list(APPEND _afl_args -G "${ARG_MAX_LEN}")
    endif()
    if(ARG_DICTIONARY)
      get_filename_component(_dict "${ARG_DICTIONARY}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
      list(APPEND _afl_args -x "${_dict}")
    endif()
    add_custom_target(${_run_target}
      COMMAND "${CMAKE_COMMAND}" -E env AFL_NO_UI=1
        "${DAGFLOW_AFL_FUZZ}" ${_afl_args} -- "$<TARGET_FILE:${target}>"
      DEPENDS ${target} USES_TERMINAL VERBATIM)
    if(BUILD_TESTING)
      add_test(NAME ${_smoke_name}
        COMMAND "${DAGFLOW_AFL_SHOWMAP}" -q -i "${_corpus}"
          -o "${_artifacts}/afl-showmap" -- "$<TARGET_FILE:${target}>" @@)
      set_tests_properties(${_smoke_name} PROPERTIES LABELS "fuzz;smoke;aflpp;${DAGFLOW_FUZZ_SMOKE_LABEL}" TIMEOUT 30)
    endif()

  else()
    if(NOT _compiler_name MATCHES "^hfuzz-")
      message(FATAL_ERROR
        "honggfuzz backend requires configuring CMAKE_CXX_COMPILER to hfuzz-clang++/hfuzz-g++ before project().")
    endif()
    find_program(DAGFLOW_HONGGFUZZ NAMES honggfuzz REQUIRED NO_CMAKE_FIND_ROOT_PATH)
    # hfuzz-* adds sanitizer coverage and libhfuzz, including the persistent
    # LLVMFuzzerTestOneInput driver. Keep optional ASan/UBSan target-scoped.
    target_link_options(${target} PRIVATE ${_san_flags})
    file(MAKE_DIRECTORY "${_artifacts}/honggfuzz" "${_artifacts}/honggfuzz-smoke")
    set(_hf_args -P -i "${_corpus}" --workspace "${_artifacts}/honggfuzz"
      --run_time "${ARG_RUN_SECONDS}")
    if(ARG_MAX_LEN)
      list(APPEND _hf_args --max_file_size "${ARG_MAX_LEN}")
    endif()
    if(ARG_DICTIONARY)
      get_filename_component(_dict "${ARG_DICTIONARY}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
      list(APPEND _hf_args -w "${_dict}")
    endif()
    add_custom_target(${_run_target}
      COMMAND "${DAGFLOW_HONGGFUZZ}" ${_hf_args} -- "$<TARGET_FILE:${target}>"
      DEPENDS ${target} USES_TERMINAL VERBATIM)
    if(BUILD_TESTING)
      add_test(NAME ${_smoke_name}
        COMMAND "${DAGFLOW_HONGGFUZZ}" -P -i "${_corpus}"
          --workspace "${_artifacts}/honggfuzz-smoke" --run_time 1 --iterations 1
          -- "$<TARGET_FILE:${target}>")
      set_tests_properties(${_smoke_name} PROPERTIES LABELS "fuzz;smoke;honggfuzz;${DAGFLOW_FUZZ_SMOKE_LABEL}" TIMEOUT 30)
    endif()
  endif()

  set_property(GLOBAL APPEND PROPERTY DAGFLOW_FUZZ_TARGETS ${target})
  if(TARGET ${_run_target})
    set_property(GLOBAL APPEND PROPERTY DAGFLOW_FUZZ_RUN_TARGETS ${_run_target})
  endif()
  if(BUILD_TESTING)
    set_property(GLOBAL APPEND PROPERTY DAGFLOW_FUZZ_SMOKE_TESTS ${_smoke_name})
  endif()
  _dagflow_project_fuzzing_finalize()
endfunction()

# Each registration becomes its own dependency, so calls from different
# subdirectories compose without directory-local command-list state.
function(dagflow_pgo_workload target)
  if(NOT TARGET ${target})
    message(FATAL_ERROR "PGO workload target does not exist: ${target}")
  endif()
  dagflow_get_target_setting(${target} PGO_MODE _pgo_mode)
  if(NOT _pgo_mode STREQUAL "generate")
    return()
  endif()
  dagflow_get_target_setting(${target} PGO_DIR _pgo_dir)
  get_property(_registered_pgo_dir GLOBAL PROPERTY DAGFLOW_REGISTERED_PGO_DIR)
  if(_registered_pgo_dir AND NOT _registered_pgo_dir STREQUAL _pgo_dir)
    message(FATAL_ERROR "PGO workloads in one build must share PGO_DIR: ${_registered_pgo_dir} vs ${_pgo_dir}")
  endif()
  set_property(GLOBAL PROPERTY DAGFLOW_REGISTERED_PGO_DIR "${_pgo_dir}")
  get_target_property(_type ${target} TYPE)
  if(NOT _type STREQUAL "EXECUTABLE")
    message(FATAL_ERROR "PGO workload must be an executable: ${target}")
  endif()
  if(NOT TARGET dagflow_pgo_train)
    add_custom_target(dagflow_pgo_train)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
      get_filename_component(_compiler_dir "${CMAKE_CXX_COMPILER}" DIRECTORY)
      string(REGEX MATCH "^[0-9]+" _compiler_major "${CMAKE_CXX_COMPILER_VERSION}")
      find_program(DAGFLOW_LLVM_PROFDATA NAMES llvm-profdata-${_compiler_major} llvm-profdata
        HINTS "${_compiler_dir}" REQUIRED NO_CMAKE_FIND_ROOT_PATH)
      set(DAGFLOW_PGO_MERGED_PROFILE "${_pgo_dir}/merged.profdata"
        CACHE FILEPATH "Output of dagflow_pgo_merge")
      set(_merge ${CMAKE_COMMAND} "-DPROFILE_DIR=${_pgo_dir}"
        "-DPROFILE_OUTPUT=${DAGFLOW_PGO_MERGED_PROFILE}"
        "-DPROFDATA=${DAGFLOW_LLVM_PROFDATA}"
        -P "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../benchmark/MergeProfiles.cmake")
      add_custom_target(dagflow_pgo_merge_only COMMAND ${_merge} USES_TERMINAL VERBATIM)
      add_custom_target(dagflow_pgo_merge COMMAND ${_merge}
        DEPENDS dagflow_pgo_train USES_TERMINAL VERBATIM)
    endif()
  endif()
  get_property(_count GLOBAL PROPERTY DAGFLOW_PGO_WORKLOAD_COUNT)
  if(NOT _count)
    set(_count 0)
  endif()
  math(EXPR _next "${_count} + 1")
  set_property(GLOBAL PROPERTY DAGFLOW_PGO_WORKLOAD_COUNT "${_next}")
  set(_workload "dagflow_pgo_workload_${_next}")
  set(_content)
  dagflow_append_setting(_content EXECUTABLE "$<TARGET_FILE:${target}>")
  dagflow_target_execution(${target} _runnable _emulator)
  dagflow_append_setting(_content EXECUTION_BLOCKED "$<NOT:$<BOOL:${_runnable}>>")
  dagflow_append_setting(_content EMULATOR "${_emulator}")
  dagflow_append_setting(_content ARGS "${ARGN}")
  dagflow_append_setting(_content ENVIRONMENT "${_dagflow_pgo_environment}")
  if(NOT _dagflow_pgo_workdir)
    set(_dagflow_pgo_workdir "${CMAKE_CURRENT_BINARY_DIR}")
  endif()
  if(NOT _dagflow_pgo_timeout)
    set(_dagflow_pgo_timeout "${DAGFLOW_RUN_TIMEOUT}")
  endif()
  dagflow_append_setting(_content WORKING_DIRECTORY "${_dagflow_pgo_workdir}")
  dagflow_append_setting(_content TIMEOUT "${_dagflow_pgo_timeout}")
  dagflow_append_setting(_content REPEATS 1)
  dagflow_append_setting(_content WARMUP 0)
  dagflow_append_setting(_content SCENARIO "${_workload}")
  dagflow_append_setting(_content PROFILE "${DAGFLOW_PROFILE}")
  dagflow_append_setting(_content CONFIG "$<CONFIG>")
  dagflow_append_setting(_content COMPILER "${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
  dagflow_append_setting(_content SOURCE_DIR "${CMAKE_SOURCE_DIR}")
  dagflow_append_setting(_content RESULT_ROOT "${DAGFLOW_RESULTS_DIR}/pgo/${_workload}")
  set(_config "${CMAKE_CURRENT_BINARY_DIR}/scenarios/$<CONFIG>/${_workload}.cmake")
  file(GENERATE OUTPUT "${_config}" CONTENT "${_content}")
  add_custom_target(${_workload} COMMAND ${CMAKE_COMMAND} "-DRUN_CONFIG=${_config}"
    -P "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../benchmark/RunWorkload.cmake"
    DEPENDS ${target} USES_TERMINAL VERBATIM)
  # Training order is deterministic even with a parallel build.
  if(_count GREATER 0)
    add_dependencies(${_workload} dagflow_pgo_workload_${_count})
  endif()
  add_dependencies(dagflow_pgo_train ${_workload})
endfunction()
