cmake_minimum_required(VERSION 3.26)
include("${CONFIG}")
execute_process(COMMAND "${CMAKE_COMMAND}" "-DHARNESS_CONFIG=${CONFIG}"
  -P "${SOURCE_DIR}/cmake/dagflow/benchmark/HarnessCMake.cmake"
  RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
if(NOT "${rc}" STREQUAL "0")
  message(FATAL_ERROR "Native campaign failed: ${out}\n${err}")
endif()
file(READ "${HARNESS_OUTPUT}/summary.json" summary)
file(READ "${HARNESS_OUTPUT}/manifest.json" manifest)
string(JSON status GET "${summary}" status)
string(JSON count LENGTH "${summary}" cases)
string(JSON marker GET "${manifest}" metadata migration_test)
string(JSON args GET "${manifest}" cases external-handles-1 args)
if(NOT status STREQUAL "passed" OR NOT count EQUAL 3 OR NOT marker STREQUAL "native"
    OR NOT args MATCHES "--workers")
  message(FATAL_ERROR "Campaign summary/provenance is incomplete")
endif()
file(STRINGS "${HARNESS_OUTPUT}/runs.jsonl" runs)
list(LENGTH runs run_count)
if(NOT run_count EQUAL 6)
  message(FATAL_ERROR "Expected two measured runs for each of three cases")
endif()
foreach(row IN LISTS runs)
  string(JSON warmup GET "${row}" warmup)
  string(JSON status GET "${row}" output status)
  if(warmup OR NOT status STREQUAL "ok")
    message(FATAL_ERROR "Unexpected campaign run: ${row}")
  endif()
endforeach()

set(base "${HARNESS_OUTPUT}/summary.json")
function(compare candidate expected)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DBASELINE=${base}"
    "-DCANDIDATE=${candidate}" -DMAX_REGRESSION_PERCENT=0
    -P "${SOURCE_DIR}/cmake/CompareDagFlow.cmake"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(expected STREQUAL "pass" AND NOT "${result}" STREQUAL "0")
    message(FATAL_ERROR "Identical campaigns rejected: ${output}\n${error}")
  elseif(expected STREQUAL "fail" AND "${result}" STREQUAL "0")
    message(FATAL_ERROR "Invalid campaign comparison accepted")
  endif()
endfunction()
compare("${base}" pass)
set(candidate "${HARNESS_OUTPUT}/candidate")
file(MAKE_DIRECTORY "${candidate}")
file(WRITE "${candidate}/manifest.json" "${manifest}")
string(JSON value GET "${summary}" cases external-handles-1 metrics run_p50_us median)
math(EXPR slower "${value}*2")
string(JSON modified SET "${summary}" cases external-handles-1 metrics run_p50_us median "${slower}")
file(WRITE "${candidate}/summary.json" "${modified}")
compare("${candidate}/summary.json" fail)
file(WRITE "${candidate}/summary.json" "${summary}")
string(JSON modified SET "${manifest}" cases external-handles-1 args 3 "\"99\"")
file(WRITE "${candidate}/manifest.json" "${modified}")
compare("${candidate}/summary.json" fail)
string(JSON modified SET "${summary}" status "\"failed\"")
file(WRITE "${candidate}/summary.json" "${modified}")
compare("${candidate}/summary.json" fail)
message(STATUS "Native campaign, provenance and comparison checks passed")
