cmake_minimum_required(VERSION 3.26)
file(READ "${CHECK_BINARY}/CMakeCache.txt" _cache)
if(CHECK_PRESET MATCHES "^(core|runtime-check)$")
  if(_cache MATCHES "CMAKE_TOOLCHAIN_FILE:[^=]*=[^\n]+" OR EXISTS "${CHECK_BINARY}/_deps")
    message(FATAL_ERROR "Dependency-free build selected a toolchain or downloaded dependencies")
  endif()
else()
  if(CHECK_PRESET STREQUAL "mimalloc")
    set(_package mimalloc)
  else()
    set(_package TBB)
  endif()
  string(REGEX MATCH "${_package}_DIR:[^=]*=([^\n]+)" _match "${_cache}")
  set(_directory "${CMAKE_MATCH_1}")
  file(REAL_PATH "${CHECK_BINARY}/vcpkg_installed" _installed)
  cmake_path(IS_PREFIX _installed "${_directory}" NORMALIZE _managed)
  if(NOT _match OR NOT _managed)
    message(FATAL_ERROR "${_package} came from '${_directory}', expected ${_installed}")
  endif()
  file(GLOB _ready "${CHECK_BINARY}/_deps/vcpkg-*/.boilerplate-ready")
  if(NOT _ready)
    message(FATAL_ERROR "CI did not exercise automatic vcpkg provisioning")
  endif()
endif()
