cmake_minimum_required(VERSION 3.26)
function(run_json output)
  execute_process(COMMAND "${BINARY}" ${ARGN} RESULT_VARIABLE _rc
    OUTPUT_VARIABLE _out ERROR_VARIABLE _err TIMEOUT 45 OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(NOT "${_rc}" STREQUAL "0")
    message(FATAL_ERROR "${BINARY} ${ARGN}: ${_rc}\n${_err}")
  endif()
  string(REPLACE "\n" ";" _rows "${_out}")
  set(${output} "${_rows}" PARENT_SCOPE)
endfunction()

function(check_field json expected)
  string(JSON _actual GET "${json}" ${ARGN})
  if(NOT "${_actual}" STREQUAL "${expected}")
    message(FATAL_ERROR "${ARGN}: expected '${expected}', got '${_actual}'\n${json}")
  endif()
endfunction()

function(check_invalid)
  execute_process(COMMAND "${BINARY}" ${BASE} ${ARGN} RESULT_VARIABLE _rc
    OUTPUT_VARIABLE _out ERROR_VARIABLE _err TIMEOUT 5)
  if(NOT DEFINED INVALID_EXIT_CODE)
    set(INVALID_EXIT_CODE 2)
  endif()
  if(NOT "${_rc}" STREQUAL "${INVALID_EXIT_CODE}")
    message(FATAL_ERROR "Expected CLI rejection (${INVALID_EXIT_CODE}) for ${ARGN}: ${_rc}\n${_out}\n${_err}")
  endif()
endfunction()

function(check_checksum key value)
  get_property(_set GLOBAL PROPERTY "checksum_${key}" SET)
  if(_set)
    get_property(_expected GLOBAL PROPERTY "checksum_${key}")
    if(NOT "${value}" STREQUAL "${_expected}")
      message(FATAL_ERROR "Checksum changed for ${key}: ${_expected} -> ${value}")
    endif()
  else()
    set_property(GLOBAL PROPERTY "checksum_${key}" "${value}")
  endif()
endfunction()
