include("${CMAKE_CURRENT_LIST_DIR}/JsonChecks.cmake")
set(BASE --json --tasks 37 --warmup 1 --warmup-ms 0 --repeats 2 --bursts 2 --idle-us 100 --verify exact)
function(check_result row)
  check_field("${row}" ok status)
  check_field("${row}" ON duration_satisfied)
  string(JSON samples LENGTH "${row}" samples)
  check_field("${row}" "${samples}" sample_count)
  string(JSON diagnostics GET "${row}" diagnostics)
  string(JSON logical GET "${row}" logical_tasks)
  math(EXPR last "${samples}-1")
  set(total 0)
  foreach(i RANGE 0 ${last})
    string(JSON sample GET "${row}" samples ${i})
    foreach(key elapsed_us drain_tail_us last_finish_us)
      string(JSON ${key} GET "${sample}" ${key})
    endforeach()
    if(elapsed_us LESS_EQUAL 0 OR drain_tail_us LESS 0 OR last_finish_us GREATER elapsed_us)
      message(FATAL_ERROR "Invalid timing boundaries: ${sample}")
    endif()
    # Check the sum to one microsecond per sample without floating-point math().
    string(REGEX REPLACE "\\..*" "" integral "${elapsed_us}")
    math(EXPR total "${total}+${integral}")
    string(JSON starts LENGTH "${sample}" start_latency_us)
    string(JSON finishes LENGTH "${sample}" finish_latency_us)
    if(NOT starts EQUAL finishes)
      message(FATAL_ERROR "Mismatched latency arrays")
    endif()
    if(starts GREATER 0)
      math(EXPR end "${starts}-1")
      foreach(j RANGE 0 ${end})
        string(JSON start GET "${sample}" start_latency_us ${j})
        string(JSON finish GET "${sample}" finish_latency_us ${j})
        if(start LESS 0 OR finish LESS start)
          message(FATAL_ERROR "Invalid task timestamps")
        endif()
      endforeach()
    endif()
    if(diagnostics)
      check_field("${sample}" "${logical}" counts packets)
      check_field("${sample}" "${logical}" counts executed)
      string(JSON external GET "${sample}" counts external_submit)
      string(JSON worker GET "${sample}" counts worker_submit)
      math(EXPR submitted "${external}+${worker}")
      if(NOT submitted EQUAL logical)
        message(FATAL_ERROR "Submission accounting mismatch")
      endif()
    endif()
  endforeach()
  string(JSON measured GET "${row}" measured_us)
  math(EXPR ceiling "${total}+${samples}")
  if(measured LESS total OR measured GREATER ceiling)
    message(FATAL_ERROR "Measured duration does not match samples")
  endif()
endfunction()
foreach(workers 1 4)
  run_json(rows ${BASE} --scenario all --workers ${workers} --producers 3 --latency --sample-stride 1)
  list(LENGTH rows count)
  if(NOT count EQUAL 7)
    message(FATAL_ERROR "Expected seven stress scenarios")
  endif()
  foreach(row IN LISTS rows)
    check_result("${row}")
    string(JSON scenario GET "${row}" scenario)
    set(expected 37)
    if(scenario STREQUAL "local-overflow")
      set(expected 38)
    elseif(scenario STREQUAL "nested-helping")
      set(expected 74)
    elseif(scenario STREQUAL "mixed-chaos")
      set(expected 60)
    endif()
    check_field("${row}" "${expected}" logical_tasks)
    math(EXPR expected "2*${expected}")
    check_field("${row}" "${expected}" latency_sample_count)
    string(JSON checksum GET "${row}" checksum)
    check_checksum("stress_${scenario}" "${checksum}")
  endforeach()
endforeach()
foreach(batch 0 1 16 64)
  foreach(mode persistent fresh)
    run_json(row ${BASE} --scenario external-contention --workers 2 --producers 3
      --submit-batch ${batch} --producer-mode ${mode} --placement none)
    check_result("${row}")
    string(JSON checksum GET "${row}" checksum)
    check_checksum(stress_batch "${checksum}")
  endforeach()
endforeach()
run_json(row ${BASE} --scenario mixed-chaos --workers 2 --fanout 0 --submit-batch 32)
check_result("${row}")
check_field("${row}" 40 logical_tasks)
check_field("${row}" 0 submit_batch)
run_json(row ${BASE} --scenario idle-burst --workers 1 --idle-us 10000 --min-ms 1 --max-samples 1000)
string(JSON measured GET "${row}" measured_us)
if(measured LESS 1000)
  message(FATAL_ERROR "Active duration minimum was not reached")
endif()
run_json(row ${BASE} --scenario idle-burst --workers 1 --min-ms 60000 --max-samples 2)
check_field("${row}" OFF duration_satisfied)
run_json(row ${BASE} --scenario local-overflow --workers 1 --tasks 65536 --warmup 0 --repeats 1)
check_result("${row}")
string(JSON diagnostics GET "${row}" diagnostics)
if(diagnostics)
  check_field("${row}" 0 counts inline_execute)
  check_field("${row}" 48128 counts overflow_push)
  check_field("${row}" 48128 counts overflow_acquire)
  check_field("${row}" 1024 counts local_push)
  check_field("${row}" 1 counts cross_thread_free)
endif()
check_invalid(--workers 0)
check_invalid(--producers 0)
check_invalid(--tasks -1)
check_invalid(--submit-batch 65)
check_invalid(--verify yes)
check_invalid(--perf-control-fd 1)
check_invalid(--worker-cpus 0,0)
message(STATUS "Stress accounting, timestamps, duration and CLI checks passed")
