include_guard(GLOBAL)

# Programs used by the build run on the host, even if a caller changes the
# toolchain's default program search mode. Libraries/packages keep target roots.
function(dagflow_find_host_program output)
  find_program(${output} ${ARGN} NO_CMAKE_FIND_ROOT_PATH)
  set(${output} "${${output}}" PARENT_SCOPE)
endfunction()

function(dagflow_add_host_tool target)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "" "" "NAMES;HINTS")
  if(ARG_UNPARSED_ARGUMENTS OR NOT ARG_NAMES)
    message(FATAL_ERROR "dagflow_add_host_tool requires NAMES [HINTS]")
  endif()
  dagflow_find_host_program(_program NAMES ${ARG_NAMES} HINTS ${ARG_HINTS} NO_CACHE REQUIRED)
  add_executable(${target} IMPORTED GLOBAL)
  set_target_properties(${target} PROPERTIES IMPORTED_LOCATION "${_program}" DAGFLOW_HOST_TOOL TRUE)
endfunction()

function(dagflow_target_execution target runnable emulator)
  get_target_property(_host ${target} DAGFLOW_HOST_TOOL)
  set(_emulator "")
  set(_runnable TRUE)
  if(CMAKE_CROSSCOMPILING AND NOT _host)
    get_target_property(_emulator ${target} CROSSCOMPILING_EMULATOR)
    if(NOT _emulator)
      set(_emulator "")
      set(_runnable FALSE)
    endif()
  endif()
  set(${runnable} "${_runnable}" PARENT_SCOPE)
  set(${emulator} "${_emulator}" PARENT_SCOPE)
endfunction()

function(dagflow_discover_tests target)
  dagflow_target_execution(${target} _runnable _emulator)
  if(_runnable)
    include(GoogleTest)
    gtest_discover_tests(${target} ${ARGN})
  else()
    # Do not run --gtest_list_tests on the build host without an emulator.
    dagflow_register_check(${target}_not_runnable ${target} LABELS cross google)
  endif()
endfunction()
