cmake_minimum_required(VERSION 3.26)
# Explicit campaign matrix. Presets own compiler/profile policy; no compiler
# command lines or benchmark subprocesses are reconstructed here.
if(NOT SOURCE_DIR)
  get_filename_component(SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
get_filename_component(SOURCE_DIR "${SOURCE_DIR}" ABSOLUTE)
if(NOT PRESETS)
  set(PRESETS bench-release)
endif()
if(NOT ALLOCATORS)
  set(ALLOCATORS system)
endif()
if(NOT OUTPUT_DIR)
  string(TIMESTAMP _stamp "%Y%m%d-%H%M%S" UTC)
  set(OUTPUT_DIR "${SOURCE_DIR}/out/campaigns/${_stamp}")
endif()
get_filename_component(OUTPUT_DIR "${OUTPUT_DIR}" ABSOLUTE)
if(EXISTS "${OUTPUT_DIR}")
  message(FATAL_ERROR "Choose a new OUTPUT_DIR; refusing to overwrite ${OUTPUT_DIR}")
endif()
if(NOT JOBS)
  set(JOBS 4)
endif()
if(NOT JOBS MATCHES "^[1-9][0-9]*$")
  message(FATAL_ERROR "JOBS must be a positive integer")
endif()
if(NOT CAMPAIGN_TARGET)
  set(CAMPAIGN_TARGET dagflow_campaigns)
endif()
function(run)
  execute_process(COMMAND ${ARGV} WORKING_DIRECTORY "${SOURCE_DIR}" RESULT_VARIABLE result)
  if(NOT "${result}" STREQUAL "0")
    message(FATAL_ERROR "Campaign matrix step failed (${result}): ${ARGV}")
  endif()
endfunction()
foreach(preset IN LISTS PRESETS)
  if(NOT preset MATCHES "^[a-zA-Z0-9_-]+$")
    message(FATAL_ERROR "Invalid preset: ${preset}")
  endif()
  foreach(allocator IN LISTS ALLOCATORS)
    if(NOT allocator MATCHES "^(system|mimalloc|tbbmalloc)$")
      message(FATAL_ERROR "Invalid allocator: ${allocator}")
    endif()
    set(build "${OUTPUT_DIR}/${preset}/${allocator}/build")
    set(results "${OUTPUT_DIR}/${preset}/${allocator}/results")
    run("${CMAKE_COMMAND}" --preset "${preset}" -B "${build}"
      -DDAGFLOW_BUILD_HARNESS=ON "-DDAGFLOW_ALLOCATOR=${allocator}"
      "-DBOILERPLATE_HARNESS_RESULTS_DIR=${results}" ${CONFIGURE_ARGS})
    file(STRINGS "${build}/CMakeCache.txt" _build_type REGEX "^CMAKE_BUILD_TYPE:STRING=")
    string(REPLACE "CMAKE_BUILD_TYPE:STRING=" "" _config "${_build_type}")
    if(NOT _config)
      set(_config Release)
    endif()
    run("${CMAKE_COMMAND}" --build "${build}" --config "${_config}"
      --target "${CAMPAIGN_TARGET}" --parallel "${JOBS}")
  endforeach()
endforeach()
message(STATUS "Campaign matrix results: ${OUTPUT_DIR}")
