cmake_minimum_required(VERSION 3.26)
# Compare the toolkit's fixed-point metric summaries, never wall-clock startup.
if(NOT METRIC)
  set(METRIC run_p50_us)
endif()
foreach(side BASELINE CANDIDATE)
  if(NOT EXISTS "${${side}}")
    message(FATAL_ERROR "${side} must name a campaign summary.json")
  endif()
  file(READ "${${side}}" ${side}_JSON)
  string(JSON status GET "${${side}_JSON}" status)
  if(NOT status STREQUAL "passed")
    message(FATAL_ERROR "Cannot compare failed ${side} campaign")
  endif()
  string(JSON ${side}_COUNT LENGTH "${${side}_JSON}" cases)
  get_filename_component(directory "${${side}}" DIRECTORY)
  if(NOT EXISTS "${directory}/manifest.json")
    message(FATAL_ERROR "Missing ${side} manifest.json beside the summary")
  endif()
  file(READ "${directory}/manifest.json" ${side}_MANIFEST)
endforeach()
if(NOT BASELINE_COUNT EQUAL CANDIDATE_COUNT OR BASELINE_COUNT EQUAL 0)
  message(FATAL_ERROR "Compare nonempty campaigns with identical case sets")
endif()
if(DEFINED MAX_REGRESSION_PERCENT AND NOT MAX_REGRESSION_PERCENT MATCHES "^[0-9]+$")
  message(FATAL_ERROR "MAX_REGRESSION_PERCENT must be a nonnegative integer")
endif()
math(EXPR last "${BASELINE_COUNT}-1")
set(report "case,metric,baseline_scaled,candidate_scaled,scale,change_basis_points\n")
set(failed FALSE)
foreach(i RANGE 0 ${last})
  string(JSON name MEMBER "${BASELINE_JSON}" cases ${i})
  foreach(side BASELINE CANDIDATE)
    string(JSON ${side}_VALUE GET "${${side}_JSON}" cases "${name}" metrics "${METRIC}" median)
    string(JSON ${side}_SCALE GET "${${side}_JSON}" cases "${name}" metrics "${METRIC}" scale)
    string(JSON ${side}_INVARIANTS GET "${${side}_JSON}" cases "${name}" invariants)
    string(JSON ${side}_ARGS GET "${${side}_MANIFEST}" cases "${name}" args)
  endforeach()
  if(NOT BASELINE_ARGS STREQUAL CANDIDATE_ARGS)
    message(FATAL_ERROR "Different workload arguments for ${name}")
  endif()
  if(NOT BASELINE_SCALE EQUAL CANDIDATE_SCALE OR NOT BASELINE_INVARIANTS STREQUAL CANDIDATE_INVARIANTS)
    message(FATAL_ERROR "Incompatible metric scale or workload invariants for ${name}")
  endif()
  if(BASELINE_VALUE LESS_EQUAL 0)
    message(FATAL_ERROR "Baseline ${METRIC} for ${name} must be positive")
  endif()
  # Divide before multiplying to keep timing/throughput values within int64.
  math(EXPR delta "${CANDIDATE_VALUE}-${BASELINE_VALUE}")
  math(EXPR whole "${delta}/${BASELINE_VALUE}")
  math(EXPR remainder "${delta}%${BASELINE_VALUE}")
  math(EXPR bp "${whole}*10000+${remainder}*10000/${BASELINE_VALUE}")
  string(APPEND report "${name},${METRIC},${BASELINE_VALUE},${CANDIDATE_VALUE},${BASELINE_SCALE},${bp}\n")
  message(STATUS "${name}: ${METRIC} change=${bp} bp (100 bp = 1%)")
  if(DEFINED MAX_REGRESSION_PERCENT)
    set(regression "${bp}")
    if(HIGHER_IS_BETTER)
      math(EXPR regression "-${bp}")
    endif()
    math(EXPR limit "${MAX_REGRESSION_PERCENT}*100")
    if(regression GREATER limit)
      set(failed TRUE)
    endif()
  endif()
endforeach()
if(OUTPUT)
  file(WRITE "${OUTPUT}" "${report}")
endif()
if(failed)
  message(FATAL_ERROR "Campaign regression exceeds ${MAX_REGRESSION_PERCENT}%")
endif()
