# Project-owned workload semantics; process execution stays in the toolkit.
set(DAGFLOW_CAMPAIGN_WORKERS "1;2;4" CACHE STRING "Worker counts for generated campaign cases")
set(DAGFLOW_CAMPAIGN_TASKS 512 CACHE STRING "Tasks per runtime/stress invocation")
set(DAGFLOW_CAMPAIGN_ITERATIONS "0;64" CACHE STRING "Fixed runtime payload iterations (stable across processes/builds)")
set(DAGFLOW_CAMPAIGN_REPEATS 3 CACHE STRING "Samples per benchmark process")
set(DAGFLOW_CAMPAIGN_WARMUP 1 CACHE STRING "Warmup samples per benchmark process")
set(DAGFLOW_CAMPAIGN_ROUNDS 3 CACHE STRING "Independent measured processes per case")
set(DAGFLOW_CAMPAIGN_AFFINITY inherit CACHE STRING "Campaign CPU placement: inherit, physical, none")
set(DAGFLOW_CAMPAIGN_PERF_EVENTS "" CACHE STRING "Optional perf stat events; empty disables counters")
set(DAGFLOW_CAMPAIGN_GROUP "smoke" CACHE STRING "Case group: smoke or full")
set_property(CACHE DAGFLOW_CAMPAIGN_GROUP PROPERTY STRINGS smoke full)
foreach(_field WORKERS TASKS REPEATS ROUNDS)
  foreach(_value IN LISTS DAGFLOW_CAMPAIGN_${_field})
    if(NOT _value MATCHES "^[1-9][0-9]*$")
      message(FATAL_ERROR "DAGFLOW_CAMPAIGN_${_field} must contain positive integers")
    endif()
  endforeach()
  if(NOT DAGFLOW_CAMPAIGN_${_field})
    message(FATAL_ERROR "DAGFLOW_CAMPAIGN_${_field} must not be empty")
  endif()
endforeach()
foreach(_field WARMUP ITERATIONS)
  if("${DAGFLOW_CAMPAIGN_${_field}}" STREQUAL "")
    message(FATAL_ERROR "DAGFLOW_CAMPAIGN_${_field} must not be empty")
  endif()
  foreach(_value IN LISTS DAGFLOW_CAMPAIGN_${_field})
    if(NOT _value MATCHES "^[0-9]+$")
      message(FATAL_ERROR "DAGFLOW_CAMPAIGN_${_field} must contain nonnegative integers")
    endif()
  endforeach()
endforeach()

function(dagflow_campaign_cases kind output)
  set(_cases "[]")
  set(_full "[]")
  set(_smoke "[]")
  set(_index 0)
  set(_smoke_index 0)
  list(GET DAGFLOW_CAMPAIGN_WORKERS 0 _first_workers)
  if(kind STREQUAL "stress")
    set(_scenarios external-contention external-batch hot-shard-skew local-overflow
      nested-helping mixed-chaos idle-burst)
  elseif(kind STREQUAL "api" OR kind STREQUAL "tbb")
    set(_scenarios chain independent parallel-for workflow noop)
    if(kind STREQUAL "api")
      list(APPEND _scenarios independent-batch)
    endif()
  else()
    set(_scenarios local_saturated steal_heavy external_detached external_handles
      idle_burst nested_spawn scope_recursive fanout_fanin deep_dag uneven graph_reuse
      dag_build_run graph_tokens_serial graph_tokens_parallel)
    if(kind STREQUAL "github")
      list(REMOVE_ITEM _scenarios scope_recursive)
    endif()
  endif()
  foreach(_scenario IN LISTS _scenarios)
    foreach(_workers IN LISTS DAGFLOW_CAMPAIGN_WORKERS)
      if(_scenario STREQUAL "steal_heavy" AND _workers EQUAL 1)
        continue()
      endif()
      set(_payloads 0)
      set(_modes throughput)
      if(kind STREQUAL "runtime" OR kind STREQUAL "github")
        set(_payloads ${DAGFLOW_CAMPAIGN_ITERATIONS})
        set(_modes throughput latency)
      endif()
      list(GET _payloads 0 _first_payload)
      foreach(_payload IN LISTS _payloads)
        foreach(_mode IN LISTS _modes)
          set(_args --workers ${_workers})
          if(kind STREQUAL "api" OR kind STREQUAL "tbb")
            list(APPEND _args --benchmark ${_scenario} --runs ${DAGFLOW_CAMPAIGN_REPEATS}
              --warmup ${DAGFLOW_CAMPAIGN_WARMUP} --payload-rounds 1)
          else()
            list(APPEND _args --scenario ${_scenario} --tasks ${DAGFLOW_CAMPAIGN_TASKS}
              --repeats ${DAGFLOW_CAMPAIGN_REPEATS} --warmup ${DAGFLOW_CAMPAIGN_WARMUP})
            if(kind STREQUAL "stress")
              list(APPEND _args --json --producers 2 --warmup-ms 0 --bursts 3
                --idle-us 100 --verify checksum)
            else()
              list(APPEND _args --iterations ${_payload} --idle-us 100)
              if(_mode STREQUAL "latency")
                list(APPEND _args --latency)
              endif()
              if(_scenario MATCHES "^(fanout_fanin|deep_dag|graph_tokens_serial|graph_tokens_parallel)$")
                list(APPEND _args --fresh-graph)
              endif()
            endif()
          endif()
          set(_name "${_scenario}-w${_workers}-it${_payload}-${_mode}")
          set(_json_args "[]")
          set(_arg_index 0)
          foreach(_arg IN LISTS _args)
            string(JSON _json_args SET "${_json_args}" ${_arg_index} "\"${_arg}\"")
            math(EXPR _arg_index "${_arg_index}+1")
          endforeach()
          set(_case "{\"name\":\"${_name}\",\"args\":${_json_args},\"metadata\":{\"workers\":${_workers},\"mode\":\"${_mode}\"}}")
          string(JSON _cases SET "${_cases}" ${_index} "${_case}")
          string(JSON _full SET "${_full}" ${_index} "\"${_name}\"")
          # Cover every scenario with one process setting in the quick group.
          if(_mode STREQUAL "throughput" AND _payload EQUAL _first_payload AND
              (_workers EQUAL _first_workers OR (_scenario STREQUAL "steal_heavy" AND _smoke_steal_missing)))
            string(JSON _smoke SET "${_smoke}" ${_smoke_index} "\"${_name}\"")
            math(EXPR _smoke_index "${_smoke_index}+1")
            set(_smoke_steal_missing FALSE)
          endif()
          math(EXPR _index "${_index}+1")
        endforeach()
      endforeach()
    endforeach()
    if(_scenario STREQUAL "local_saturated")
      set(_smoke_steal_missing TRUE)
    endif()
  endforeach()
  set(_path "${CMAKE_CURRENT_BINARY_DIR}/campaigns/${kind}.json")
  file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/campaigns")
  file(WRITE "${_path}" "{\"groups\":{\"smoke\":${_smoke},\"full\":${_full}},\"cases\":${_cases}}\n")
  set(${output} "${_path}" PARENT_SCOPE)
endfunction()
